### ISSUE TITLE
Crash in MediaProviderDelegate$startMonitor$1.onChange build:606

### ISSUE THREAD

**Issue by mxlius** [mozilla-tw/ScreenshotGo#353]
Fatal Exception: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/521 from pid=22929, uid=10214 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1703)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:536)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at org.mozilla.scryer.filemonitor.MediaProviderDelegate$startMonitor$1.onChange(MediaProviderDelegate.kt:25)
       at android.database.ContentObserver.onChange(ContentObserver.java:145)
       at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by weslyhuang** [comment]
S1 for crash, keep monitoring for more figures before making the priority decision.
