### ISSUE TITLE
Crash in ScreenshotFetcher.getFolders, build:606

### ISSUE THREAD

**Issue by mxlius** [mozilla-tw/ScreenshotGo#354]
Fatal Exception: java.lang.IllegalStateException: cursor.getString(cursor.…mages.ImageColumns.DATA)) must not be null
       at org.mozilla.scryer.filemonitor.ScreenshotFetcher.getFolders(ScreenshotFetcher.kt:36)
       at org.mozilla.scryer.filemonitor.ScreenshotFetcher.fetchScreenshots(ScreenshotFetcher.kt:14)
       at org.mozilla.scryer.landingpage.HomeFragment$syncAndGetNewScreenshotsFromExternal$externalList$1.doResume(HomeFragment.kt:530)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
       at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1392)
       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:257)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:852)
       at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1681)
       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1636)
       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by weslyhuang** [comment]
S1 for crash, keep monitoring for more figures before making the priority decision.
