### ISSUE TITLE
Crash in HomeFragment$createOptionsMenuSearchView$4.onClick, build:606

### ISSUE THREAD

**Issue by mxlius** [mozilla-tw/ScreenshotGo#355]
Fatal Exception: kotlin.KotlinNullPointerException
       at org.mozilla.scryer.landingpage.HomeFragment$createOptionsMenuSearchView$4.onClick(HomeFragment.kt:419)
       at android.view.View.performClick(View.java:6261)
       at android.view.View$PerformClick.run(View.java:23752)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by weslyhuang** [comment]
S1 for crash, keep monitoring for more figures before making the priority decision.
